name: libkoala
description: "Shared Library for Bear Metal Flutter Apps"
version: 0.0.1

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  crypto: ^3.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  flutter_secure_storage: ^9.2.4
  flutter_staggered_grid_view: ^0.7.0
  flutter_web_auth_2: 5.0.0-alpha.7
  http: ^1.2.2
  hive_ce: ^2.15.0
  material_symbols_icons: ^4.2892.0
  path: ^1.9.1
  path_provider: ^2.1.4
  provider: ^6.1.5
  riverpod: ^3.0.0
  riverpod_annotation: ^3.0.0
  simple_icons: ^14.6.1
  url_launcher: ^6.3.2
  universal_platform: ^1.1.0
  dio: ^5.9.0

dev_dependencies:
  build_runner: ^2.5.4
  custom_lint: ^0.8.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^3.0.0
  riverpod_lint: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/to/asset-from-package
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/to/resolution-aware-images

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/to/font-from-package
